### ISSUE TITLE
Allocating from non affine blocks ends in panic

### ISSUE THREAD

**Issue by rlguarino** [projectcalico/cni-plugin#316]
I'm seeing weird behavior on a node which does not have affine blocks assigned to it. An exerpt of the logs are here: 

```
kubelet[19840]: I0426 21:39:27.515418   27556 ipam_block_reader_writer.go:110] Getting block: 10.36.2.0/26
kubelet[19840]: I0426 21:39:27.515430   27556 etcd.go:154] Get Key: /calico/ipam/v2/assignment/ipv4/block/10.36.2.0-26
dockerd[21947]: shutting down, got signal: Terminated
kubelet[19840]: I0426 21:39:27.538429   27556 ipam.go:231] Attempting to assign 1 more addresses from non-affine blocks
kubelet[19840]: I0426 21:39:27.538451   27556 etcd.go:174] List Key: /calico/v1/ipam/
kubelet[19840]: I0426 21:39:27.557281   27556 pool.go:74] Get Pool key from /calico/v1/ipam/v4/pool/10.36.2.0-24
kubelet[19840]: I0426 21:39:27.557319   27556 etcd.go:248] Returning: []*model.KVPair{(*model.KVPair)(0xc420045ec0)}
kubelet[19840]: I0426 21:39:27.557326   27556 etcd.go:248] Returning: []*model.KVPair{(*model.KVPair)(0xc420045ec0)}
kubelet[19840]: I0426 21:39:27.557329   27556 etcd.go:248] Returning: []*model.KVPair{(*model.KVPair)(0xc420045ec0)}
kubelet[19840]: I0426 21:39:27.557333   27556 etcd.go:248] Returning: []*model.KVPair{}
kubelet[19840]: I0426 21:39:27.557336   27556 etcd.go:248] Returning: []*model.KVPair{}
kubelet[19840]: I0426 21:39:27.557339   27556 etcd.go:248] Returning: []*model.KVPair{(*model.KVPair)(0xc420045ec0)}
kubelet[19840]: I0426 21:39:27.557349   27556 ipam.go:257] Assigning from random blocks in pool 10.36.2.0/24
kubelet[19840]: I0426 21:39:27.557372   27556 ipam.go:462] Auto-assign from 10.36.2.192/26 - retry 0
kubelet[19840]: I0426 21:39:27.557378   27556 etcd.go:154] Get Key: /calico/ipam/v2/assignment/ipv4/block/10.36.2.192-26
kubelet[19840]: I0426 21:39:27.576701   27556 ipam.go:472] Got block: {AllocationBlock:{CIDR:{IPNet:{IP:10.36.2.192 Mask:ffffffc0}} HostAffinity:0xc4203ae540 StrictAffinity:false Allocations:[<nil> <nil> <nil> <nil>
kubelet[19840]: E0426 21:39:27.576751   27556 ipam.go:475] Error in auto assign: Block affinity (%!s(*string=0xc4203ae540)) does not match provided (host2)
kubelet[19840]: W0426 21:39:27.576762   27556 ipam.go:270] Failed to assign IPs in pool 10.36.2.0/24: Block affinity (%!s(*string=0xc4203ae540)) does not match provided (host2)
kubelet[19840]: I0426 21:39:27.576781   27556 ipam.go:279] Auto-assigned 0 out of 1 IPv4s: []
kubelet[19840]: Calico CNI IPAM assigned addresses IPv4=[] IPv6=[]
kubelet[19840]: panic: runtime error: index out of range
kubelet[19840]: goroutine 1 [running]:
kubelet[19840]: panic(0x9af180, 0xc42000a090)
kubelet[19840]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
kubelet[19840]: main.cmdAdd(0xc420277a40, 0x3, 0xa6e86a)
kubelet[19840]:         /build/calico-cni/tmp/build/gopath/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:91 +0xe40
kubelet[19840]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc42022fec0, 0xab62b0, 0xab62b8, 0xc420090058)
kubelet[19840]:         /build/calico-cni/tmp/build/gopath/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:155 +0x303
kubelet[19840]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0xab62b0, 0xab62b8)
kubelet[19840]:         /build/calico-cni/tmp/build/gopath/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:188 +0xd6
kubelet[19840]: main.main()
kubelet[19840]:         /build/calico-cni/tmp/build/gopath/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:20 +0x39

```

The strange piece is that the block generated by [generateRandomBlock's generator](https://github.com/projectcalico/libcalico-go/blob/658ba00cbe61fa2a1a61bf3c85505b6ce28251f6/lib/client/ipam_block_reader_writer.go#L303) function [here](https://github.com/projectcalico/libcalico-go/blob/658ba00cbe61fa2a1a61bf3c85505b6ce28251f6/lib/client/ipam.go#L261) seems to have a uninitialized Block affinity.

I'm using version 1.4.2 but I've looked at the code in ipam/calico-ipam.go and vendored the dep here: https://github.com/projectcalico/libcalico-go/blob/658ba00cbe61fa2a1a61bf3c85505b6ce28251f6/lib/client/ipam_block.go#L82 And it does not seem to change in any meaningful way in the current release. So I don't know if updating would fix this.

**Comment by tmjd** [comment]
@gunjan5 Are you the right one to take a look at that?

**Comment by caseydavenport** [comment]
@rlguarino can you provide any more information as to how you hit this issue? Was this using one of the `cni.projectcalico.org/ipAddrs` style annotations to assign a specific address?  What steps can we take to reproduce this?

**Comment by rlguarino** [comment]
@caseydavenport Thanks for taking a look at this. I've tried upgrading to 1.7 and the problem seems to be resolved. I might revisit this as personal exercise in debugging but the issue (whatever it was) seems to be resolved by upgrading.
