### ISSUE TITLE
CNI plugin panic during scale test

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/cni-plugin#331]
Doing a k8s scale test with k8s 1.6.2 and calico CNI 1.8.0, I see errors when creating pods, then the teardown fails with what looks like a panic in the CNI plugin

```
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: E0509 14:48:45.812616    1365 cni.go:275] Error deleting network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: E0509 14:48:45.813997    1365 remote_runtime.go:109] StopPodSandbox "7ff045ef5825f44bf12a247b4ff528081ee87a7e18171e4e7b5137217dd50259" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "client0-cali-ns-0-3900991725-ggstf_cali-ns-0" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: E0509 14:48:45.814042    1365 kuberuntime_manager.go:784] Failed to stop sandbox {"docker" "7ff045ef5825f44bf12a247b4ff528081ee87a7e18171e4e7b5137217dd50259"}
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: E0509 14:48:45.814282    1365 kuberuntime_manager.go:573] killPodWithSyncResult failed: failed to "KillPodSandbox" for "752f215f-34c1-11e7-8592-42010af00184" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"client0-cali-ns-0-3900991725-ggstf_cali-ns-0\" network: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: E0509 14:48:45.814403    1365 pod_workers.go:182] Error syncing pod 752f215f-34c1-11e7-8592-42010af00184 ("client0-cali-ns-0-3900991725-ggstf_cali-ns-0(752f215f-34c1-11e7-8592-42010af00184)"), skipping: failed to "KillPodSandbox" for "752f215f-34c1-11e7-8592-42010af00184" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"client0-cali-ns-0-3900991725-ggstf_cali-ns-0\" network: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
```

Near: 

```
ault-token-7d92m" (spec.Name: "default-token-7d92m") pod "1e548398-34c2-11e7-8592-42010af00184" (UID: "1e548398-34c2-11e7-8592-42010af00184").
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: panic: runtime error: invalid memory address or nil pointer dereference
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x134512a]
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: goroutine 1 [running, locked to thread]:
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*workloadEndpoints).convertKVPairToAPI(0xc420288190, 0x0, 0xc42015d240, 0x0, 0x0, 0x0)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/workloadendpoint.go:180 +0x3a
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*Client).get(0xc420427050, 0x1eeee40, 0xc42014a310, 0x1efc4c0, 0xc420288190, 0x8, 0x8, 0xc420288190, 0x0)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/client.go:290 +0xef
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*workloadEndpoints).Get(0xc420288190, 0x0, 0x0, 0xc42000e03b, 0x4, 0xc420410f00, 0x2c, 0x162b2af, 0x3, 0xc420410060, ...)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/workloadendpoint.go:71 +0xc1
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/k8s.CmdDelK8s(0xc420427050, 0x0, 0x0, 0xc42000e03b, 0x4, 0xc420410f00, 0x2c, 0x162b2af, 0x3, 0xc420410060, ...)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/k8s/k8s.go:306 +0xaa
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: main.cmdDel(0xc42042b7a0, 0x162c124, 0x5)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/calico.go:325 +0x9e8
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc42043e9c0, 0xc42042b7a0, 0x1ef1180, 0xc420018600, 0x169c470, 0x0, 0xc42024aea0)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x19f
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc42043e9c0, 0x169c468, 0x169c470, 0x1ef1180, 0xc420018600, 0xc420603f00)
May 09 14:48:45 gke-smc14-default-pool-dc39b97a-nxg9 kubelet[1365]: /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:175 +0x2af

```

**Comment by fasaxc** [comment]
Sounds like this is a dupe of this issue: https://github.com/projectcalico/libcalico-go/issues/415, which should be fixed in v1.8.1
